source/blueprints/live/__init__.py
# -*- coding: utf-8 -*-

"""
Initial blueprint module to initiate Poll blueprint.
"""

# Standard libraries import
import os

# Application modules import
import blueprints
from config import STATIC_PATH
from plugins.admin import permission_required

# Additional libraries import
from flask import Blueprint
from flask import render_template

# Initiate Blueprint object
blueprint = Blueprint(
	'live', __name__,
	static_folder=STATIC_PATH,
	template_folder=os.path.abspath(
		os.path.join(os.path.dirname(__file__), 'templates'))
)

# Routes handling modules import
from blueprints.live import result


@blueprint.route('/', methods=('GET',))
#@permission_required
def get_live():
	"""
	Return live last updated poll's results.
	"""
	poll = result.Result.get_last_poll()
	return render_template(
		'result.html',
		poll_title=poll.title,
		vote_data=result.Result.get_vote_data(poll)
	)


@blueprint.route('/image/<uid>/', methods=('GET',))
#@permission_required
def get_image(uid: str):
	"""
	Return image on page by uid.
	"""
	return render_template(
		'image.html',
		uid=uid
	)


@blueprint.route('/<uid>/', methods=('GET',))
#@permission_required
def get_results(uid: str):
	"""
	Return poll's results.
	"""
	return result.Result.get_results(
		result.Result.get_poll(uid))


@blueprint.route('/last/', methods=('GET',))
#@permission_required
def get_last_results():
	"""
	Return last updated poll's results.
	"""
	return result.Result.get_last_results()

source/blueprints/root/__init__.py
# -*- coding: utf-8 -*-

"""
Initial blueprint module to initiate base blueprint.
"""

# Standard libraries import
import os
import logging

# Application modules import
import blueprints
from blueprints.__form__ import FileForm
from config import STATIC_PATH
from config import TEMPLATE_PATH
from plugins.admin import permission_required

# Additional libraries import
from flask import Blueprint
from flask import render_template
from flask import redirect
from flask import request
from flask import url_for
from flask_login import logout_user
from flask_login import current_user

# Initiate Blueprint object
blueprint = Blueprint(
	'root', __name__,
	static_folder=STATIC_PATH,
	template_folder=os.path.abspath(
		os.path.join(os.path.dirname(__file__), 'templates'))
)

# Routes handling modules import
from blueprints.root import sign_form


@blueprint.route('/sign-in/', methods=('GET','POST'))
@blueprint.route('/identica/<url_token>/', methods=('GET','POST'))
@blueprint.route('/', methods=('GET','POST'))
def get_home(url_token: str = None):
	"""
	Return home page.
	"""
	if current_user.is_authenticated:
		return render_template('home.html')
	form = sign_form.SignInForm(url_token)
	if form.validate_on_submit():
		return form.authenticate() or \
			render_template(
				'home.html',
				form=form
			)
	return render_template(
		'home.html',
		form=form
	)


@blueprint.route('/sign-out/', methods=('GET',))
@permission_required
def sign_out():
	"""
	Return home page after sign out.
	"""
	logout_user()
	return redirect(url_for('root.get_home'))


@blueprint.route('/upload/', methods=('POST',))
@permission_required
def upload():
	"""
	Upload file and return result.
	"""
	return FileForm().upload()


@blueprint.route('/download/<uid>/', methods=('GET',))
#@permission_required
def download(uid: str):
	"""
	Return file by link.
	"""
	return FileForm.download(uid)


@blueprint.route('/site-map/', methods=('GET',))
def site_map():
	links = []
	for rule in blueprints.application.url_map.iter_rules():
		links.append(
			(
				rule.rule,
				rule.endpoint,
				str(rule.arguments) if len(rule.arguments) > 0 else None
			)
		)
	return {'links': links}, 200


@blueprints.application.errorhandler(400) # HTTP_400_BAD_REQUEST
@blueprints.application.errorhandler(401) # HTTP_401_UNAUTHORIZED
@blueprints.application.errorhandler(403) # HTTP_403_FORBIDDEN
@blueprints.application.errorhandler(404) # HTTP_404_NOT_FOUND
@blueprints.application.errorhandler(405) # HTTP_405_METHOD_NOT_ALLOWED
@blueprints.application.errorhandler(406) # HTTP_406_NOT_ACCEPTABLE
@blueprints.application.errorhandler(408) # HTTP_408_REQUEST_TIMEOUT
@blueprints.application.errorhandler(409) # HTTP_409_CONFLICT
@blueprints.application.errorhandler(410) # HTTP_410_GONE
@blueprints.application.errorhandler(411) # HTTP_411_LENGTH_REQUIRED
@blueprints.application.errorhandler(412) # HTTP_412_PRECONDITION_FAILED
@blueprints.application.errorhandler(413) # HTTP_413_REQUEST_ENTITY_TOO_LARGE
@blueprints.application.errorhandler(414) # HTTP_414_REQUEST_URI_TOO_LONG
@blueprints.application.errorhandler(415) # HTTP_415_UNSUPPORTED_MEDIA_TYPE
@blueprints.application.errorhandler(416) # HTTP_416_REQUESTED_RANGE_NOT_SATISFIABLE
@blueprints.application.errorhandler(417) # HTTP_417_EXPECTATION_FAILED
@blueprints.application.errorhandler(428) # HTTP_428_PRECONDITION_REQUIRED
@blueprints.application.errorhandler(429) # HTTP_429_TOO_MANY_REQUESTS
@blueprints.application.errorhandler(431) # HTTP_431_REQUEST_HEADER_FIELDS_TOO_LARGE
@blueprints.application.errorhandler(500) # HTTP_500_INTERNAL_SERVER_ERROR
@blueprints.application.errorhandler(501) # HTTP_501_NOT_IMPLEMENTED
@blueprints.application.errorhandler(502) # HTTP_502_BAD_GATEWAY
@blueprints.application.errorhandler(503) # HTTP_503_SERVICE_UNAVAILABLE
@blueprints.application.errorhandler(504) # HTTP_504_GATEWAY_TIMEOUT
@blueprints.application.errorhandler(505) # HTTP_505_HTTP_VERSION_NOT_SUPPORTED
def get_error(error):
	"""
	Return error page with error code.
	"""
	if getattr(error, 'code', 0) == 400:
		logging.error('Error Handler', exc_info=1)
	return render_template(
		'error.html', error_code=getattr(error, 'code', 0)
	), getattr(error, 'code', 200)

source/templates/footer.html
{%- if action_items -%}
	<div class="footer-placeholder"></div>
	<footer class="shadow py-2">
		<div class="ui-background"></div>
		{{ footer_collapse }}
		<div class="ui-foreground d-flex w-100 justify-content-between align-items-center">
			<div class="d-flex w-100 justify-content-start align-items-center">
				{{ action_items }}
			</div>
			<div class="d-flex w-100 justify-content-end align-items-center">
				{{ additional_items }}
			</div>
		</div>
	</footer>
{%- endif -%}

source/templates/header.html
{%- set logout_span -%}<span class="nav-icon oi oi-account-logout"></span>{%- endset -%}
{%- set menu_items = [ (url_for('live.get_live'), __('Live')), (url_for('poll.get_catalog'), __('Catalog')), (url_for('root.sign_out'), logout_span) ] -%}
<header class="sticky-top shadow">
	<div class="ui-background"></div>
	<div class="ui-foreground d-flex w-100 justify-content-between align-items-center">
		<div>
			<a class="nav-title" href="{{ url_for('root.get_home') }}">
				{%- if title -%}
					<h1 class="d-inline-block m-0">{{ __(title) }}</h1>
				{%- else -%}
					<h1 class="d-inline-block m-0">{{ basename }}</h1>
				{%- endif -%}
			</a>
		</div>
		<div class="nav-foreground d-flex justify-content-end align-items-center">
			{{ nav_items }}
			{%- if current_user.is_authenticated -%}
				{%- for menu_link, menu_text in menu_items -%}
					<a class="nav-item d-none d-md-inline-block" href="{{ menu_link }}">{{ menu_text }}</a>
				{%- endfor -%}
				<a class="nav-item d-inline-block d-md-none" href="#collapseMenu" data-bs-toggle="collapse"><span class="nav-icon oi oi-menu"></span></a>
			{%- endif -%}
		</div>
	</div>
	{{ header_collapse }}
	<div id="collapseMenu" class="collapse ui-foreground">
		<div class="collapse-separator d-block d-md-none"></div>
		{%- if current_user.is_authenticated -%}
			{%- for menu_link, menu_text in menu_items -%}
				<a class="nav-item d-block d-md-none" href="{{ menu_link }}">{{ menu_text }}</a>
			{%- endfor -%}
		{%- endif -%}
	</div>
</header>

source/templates/layout.html
{%- set basename = __config('name') -%}
<!DOCTYPE html>
<html>
	<head lang="en">
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous"/>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.8.1/dropzone.css" integrity="sha512-7uSoC3grlnRktCWoO4LjHMjotq8gf9XDFQerPuaph+cqR7JC9XKGdvN+UwZMC14aAaBDItdRj3DcSDs4kMWUgg==" crossorigin="anonymous" />
		<link rel="preconnect" href="https://fonts.gstatic.com">
		<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;400;700&display=swap" rel="stylesheet">
		<link rel="stylesheet" href="{{ url_for('static', filename='css/layout.css') }}"/>
		<link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}?v=1.1"/>
 		{%- block style -%}{%- endblock -%}
		<title>{{ __(basename) }}{%- if title -%}{{ ': ' + title }}{%- endif -%}</title>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.5.4/umd/popper.min.js" integrity="sha512-7yA/d79yIhHPvcrSiB8S/7TyX0OxlccU8F/kuB8mHYjLlF1MInPbEohpoqfz0AILoq5hoD7lELZAYYHbyeEjag==" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment-with-locales.min.js" integrity="sha256-wdiCkHJlqyoIJxG49WbDO0D3/EnppQp6GVOGQA6PBkA=" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.31/moment-timezone-with-data.min.js" integrity="sha256-E10X63Z5YvTXDfZjb0Kqd7FOo6a/gE7hFGcYm63PLmM=" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.8.1/min/dropzone.min.js" integrity="sha512-OTNPkaN+JCQg2dj6Ht+yuHRHDwsq1WYsU6H0jDYHou/2ZayS2KXCfL28s/p11L0+GSppfPOqwbda47Q97pDP9Q==" crossorigin="anonymous"></script>
		<script src="{{ url_for('static', filename='js/collapseHideOther.js') }}"></script>
		<script src="{{ url_for('static', filename='js/readableTimestamp.js') }}"></script>
    {%- block script -%}{%- endblock -%}
	</head>
	<body>
		<div class="container-fluid">
			<div class="row">
				{%- include "header.html" -%}
				{%- block content -%}{%- endblock -%}
				{%- include "footer.html" -%}
			<div>
		</div>
    {%- block body_script -%}{%- endblock -%}
	</body>
</html>

source/templates/layout_image.html
{%- set basename = __config('name') -%}
<!DOCTYPE html>
<html>
	<head lang="en">
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
		<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}"/>
		<link rel="stylesheet" href="{{ url_for('static', filename='css/layout.css') }}"/>
		<link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}?v=1.1"/>
 		{%- block style -%}{%- endblock -%}
		<title>{{ __(basename) }}{%- if title -%}{{ ': ' + title }}{%- endif -%}</title>
		<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
		{%- block script -%}{%- endblock -%}
	</head>
	<body style="background: transparent;">
		<div class="container-fluid">
			<div class="row">
				{%- block content -%}{%- endblock -%}
			<div>
		</div>
    {%- block body_script -%}{%- endblock -%}
	</body>
</html>