source/blueprints/live/__init__.py
# -*- coding: utf-8 -*-

"""
Initial blueprint module to initiate Poll blueprint.
"""

# Standard libraries import
import os

# Application modules import
import blueprints
from config import STATIC_PATH
from plugins.admin import permission_required

# Additional libraries import
from flask import Blueprint
from flask import render_template

# Initiate Blueprint object
blueprint = Blueprint(
	'live', __name__,
	static_folder=STATIC_PATH,
	template_folder=os.path.abspath(
		os.path.join(os.path.dirname(__file__), 'templates'))
)

# Routes handling modules import
from blueprints.live import result


@blueprint.route('/', methods=('GET',))
#@permission_required
def get_live():
	"""
	Return live last updated poll's results.
	"""
	poll = result.Result.get_last_poll()
	return render_template(
		'result.html',
		poll_title=poll.title,
		vote_data=result.Result.get_vote_data(poll)
	)


@blueprint.route('/image/<uid>/', methods=('GET',))
#@permission_required
def get_image(uid: str):
	"""
	Return image on page by uid.
	"""
	return render_template(
		'image.html',
		uid=uid
	)


@blueprint.route('/<uid>/', methods=('GET',))
#@permission_required
def get_results(uid: str):
	"""
	Return poll's results.
	"""
	return result.Result.get_results(
		result.Result.get_poll(uid))


@blueprint.route('/last/', methods=('GET',))
#@permission_required
def get_last_results():
	"""
	Return last updated poll's results.
	"""
	return result.Result.get_last_results()

source/blueprints/live/templates/image.html
{%- extends "layout_image.html" -%}
{%- set hidden_content = True -%}
{%- set title = 'Image' -%}
{%- block content -%}
	<img class="blurred-fullpage-image" src="{{ url_for('root.download', uid=uid) }}" />
	<img class="fullpage-image" src="{{ url_for('root.download', uid=uid) }}" />
{%- endblock -%}
{%- set action_items -%}
	<a class="nav-item pl-zero" href="{{ url_for('live.get_live') }}"><span class="nav-icon oi oi-arrow-thick-left"></span><div class="d-none d-sm-inline">{{ __('Live') }}</div></a>
{%- endset -%}

source/blueprints/live/templates/result.html
{%- extends "layout.html" -%}
{%- set hidden_content = True -%}
{%- set title = 'Live' -%}
{%- block content -%}
	{%- if vote_data -%}
		<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-2 m-0">
			{%- for option in vote_data['results'] -%}
				<div class="card shadow p-2">
					{%- if option['image']['uid'] -%}
						<a href="{{ url_for('live.get_image', uid=option['image']['uid']) }}" target="_blank" class="stretched-link"></a>
					{%- endif -%}
					<div class="ui-background"></div>
					<div class="ui-foreground">
						<div class="row g-2">
							<div class="col-12 col-sm-6 col-md-4 col-lg-3">
								<div class="catalog-image">
									{%- if option['image']['uid'] -%}
										<img src="{{ url_for('root.download', uid=option['image']['uid']) }}"/>
									{%- endif -%}
								</div>
							</div>
							<div class="col-12 col-sm-6 col-md-8 col-lg-9">
								<div class="d-flex align-items-start flex-column h-100 w-100">
									<div class="d-flex justify-content-between align-items-center w-100">
										<h5 class="text-left">{{ option['title'] }} <small class="text-muted">({{ option['count'] }})</small></h5>
										<h5 class="text-left">{{ option['percent'] }}%</h5>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			{%- endfor -%}
		</div>
	{%- else -%}
		<div class="row row-cols-1 g-2 m-0">
			<div class="card shadow p-2">
				<div class="ui-background"></div>
				<div class="ui-foreground">
					<div class="text-center w-100">{{ __('No vote data found') }}</div>
				</div>
			</div>
		</div>
	{%- endif -%}
{%- endblock -%}
{%- set action_items -%}
	{{ poll_title + ' (' + __('total votes' + ': ') }}{%- if vote_data -%}{{ vote_data['voters']['count']}}{%- else -%}{{ 0 }}{%- endif -%}{{ ')' }}
{%- endset -%}
{%- set additional_items -%}
	<a class="nav-item pl-zero" href="{{ url_for('live.get_last_results') }}" target="_blank"><span class="nav-icon oi oi-spreadsheet"></span><div class="d-none d-sm-inline">{{ __('Raw') }}</div></a>
{%- endset -%}