source/blueprints/poll/__init__.py
# -*- coding: utf-8 -*-

"""
Initial blueprint module to initiate Poll blueprint.
"""

# Standard libraries import
import os

# Application modules import
import blueprints
from plugins.admin import permission_required
from config import STATIC_PATH

# Additional libraries import
from flask import Blueprint
from flask import url_for
from flask import request
from flask import redirect
from flask import render_template
from flask_login import current_user

# Initiate Blueprint object
blueprint = Blueprint(
	'poll', __name__,
	static_folder=STATIC_PATH,
	template_folder=os.path.abspath(
		os.path.join(os.path.dirname(__file__), 'templates'))
)

# Routes handling modules import
from blueprints.poll import poll_catalog
from blueprints.poll import poll_history
from blueprints.poll import poll_form
from blueprints.poll import option_catalog
from blueprints.poll import option_history
from blueprints.poll import option_form


@blueprint.route('/', methods=('GET', 'POST'))
@blueprint.route('/catalog/', methods=('GET', 'POST'))
@permission_required
def get_catalog():
	"""
	Return poll catalog page.
	"""
	filter = poll_catalog.PollFilter()
	if filter.form_valid:
		if filter.submit.data:
			return redirect(url_for('poll.get_catalog'))
		elif filter.reset.data:
			filter.reset_fields()
			return redirect(url_for('poll.get_catalog'))
	pagination, list = poll_catalog.PollList(
		'poll.get_catalog').read_list(filter)
	return render_template(
		'poll_catalog.html',
		list=list,
		filter=filter,
		pagination=pagination
	)


@blueprint.route('/history/', methods=('GET', 'POST'))
@permission_required
def get_history():
	"""
	Return poll history page.
	"""
	filter = poll_history.PollHistoryFilter()
	if filter.form_valid:
		if filter.submit.data:
			return redirect(url_for('poll.get_history'))
		elif filter.reset.data:
			filter.reset_fields()
			return redirect(url_for('poll.get_history'))
	pagination, list = poll_history.PollHistoryList(
		'poll.get_history').read_list(filter)
	return render_template(
		'poll_history.html',
		list=list,
		filter=filter,
		pagination=pagination
	)


@blueprint.route('/create/', methods=('GET', 'POST'))
@permission_required
def create():
	"""
	Return poll create page.
	"""
	form = poll_form.PollForm()
	if form.form_valid:
		if form.submit.data:
			poll = form.create()
			poll_history.PollHistoryList.create(
				current_user.user.id, poll.id, 'create'
			)
			return redirect(url_for('poll.get_catalog'))
	return render_template(
		'poll_form.html',
		form=form,
		action=blueprints.__('Create')
	)


@blueprint.route('/update/<uid>/', methods=('GET', 'POST'))
@permission_required
def update(uid: str):
	"""
	Return poll update page.
	"""
	form = poll_form.PollForm(uid)
	if form.form_valid:
		if form.submit.data:
			poll = form.update(uid)
			poll_history.PollHistoryList.create(
				current_user.user.id, poll.id, 'update'
			)
			return redirect(url_for('poll.get_catalog'))
	return render_template(
		'poll_form.html',
		form=form,
		action=blueprints.__('Update'),
		poll_uid=uid,
		poll_active=False
	)


@blueprint.route('/results/<uid>/delete/', methods=('GET',))
@permission_required
def delete_results(uid: str):
	"""
	Delete poll's results (vote_data) by uid
	and return redirect to update poll.
	"""
	poll = poll_catalog.PollStore().set_vote_data(uid, None)
	poll_history.PollHistoryList.create(
		current_user.user.id, poll.id, 'delete results'
	)
	return redirect(url_for('poll.update', uid=uid))


@blueprint.route('/delete/<uid>/', methods=('GET',))
@permission_required
def delete(uid: str):
	"""
	Delete poll by uid and return redirect to catalog.
	"""
	poll = poll_catalog.PollList.delete(uid)
	poll_history.PollHistoryList.create(
		current_user.user.id, poll.id, 'delete'
	)
	return redirect(url_for('poll.get_catalog'))


@blueprint.route('/start/<uid>/', methods=('GET',))
@permission_required
def start(uid: str):
	"""
	Start poll by uid.
	"""
	poll = poll_catalog.PollList.start(uid)
	poll_history.PollHistoryList.create(
		current_user.user.id, poll.id, 'start'
	)
	return redirect(url_for('poll.get_catalog'))


@blueprint.route('/stop/<uid>/', methods=('GET',))
@permission_required
def stop(uid: str):
	"""
	Stop poll by uid.
	"""
	poll = poll_catalog.PollList.stop(uid)
	poll_history.PollHistoryList.create(
		current_user.user.id, poll.id, 'stop'
	)
	return redirect(url_for('poll.get_catalog'))


@blueprint.route('/<poll_uid>/option/', methods=('GET', 'POST'))
@blueprint.route('/<poll_uid>/option/catalog/', methods=('GET', 'POST'))
@permission_required
def get_option_catalog(poll_uid: str):
	"""
	Return poll's option catalog page.
	"""
	filter = option_catalog.OptionFilter()
	if filter.form_valid:
		if filter.submit.data:
			return redirect(url_for('poll.get_option_catalog', poll_uid=poll_uid))
		elif filter.reset.data:
			filter.reset_fields()
			return redirect(url_for('poll.get_option_catalog', poll_uid=poll_uid))
	reorderer = option_catalog.ReordererForm()
	if reorderer.form_valid:
		if reorderer.submit.data:
			reorderer.reorder()
			poll_catalog.PollStore().set_vote_data(poll_uid, None)
			return redirect(url_for('poll.get_option_catalog', poll_uid=poll_uid))
	pagination, list = option_catalog.OptionList(
		'poll.get_option_catalog', poll_uid).read_list(poll_uid, filter)
	poll, file = poll_catalog.PollList.read(poll_uid)
	return render_template(
		'option_catalog.html',
		list=list,
		filter=filter,
		pagination=pagination,
		reorderer=reorderer,
		poll=poll,
		file=file
	)


@blueprint.route('/<poll_uid>/option/history/', methods=('GET', 'POST'))
@permission_required
def get_option_history(poll_uid: str):
	"""
	Return poll's option history page.
	"""
	filter = option_history.OptionHistoryFilter()
	if filter.form_valid:
		if filter.submit.data:
			return redirect(url_for('poll.get_option_history', poll_uid=poll_uid))
		elif filter.reset.data:
			filter.reset_fields()
			return redirect(url_for('poll.get_option_history', poll_uid=poll_uid))
	pagination, list = option_history.OptionHistoryList(
		'poll.get_option_history', poll_uid).read_list(poll_uid, filter)
	return render_template(
		'option_history.html',
		list=list,
		filter=filter,
		pagination=pagination,
		poll_uid=poll_uid
	)


@blueprint.route('/<poll_uid>/option/create/', methods=('GET', 'POST'))
@permission_required
def create_option(poll_uid: str):
	"""
	Return poll's option create page.
	"""
	form = option_form.OptionForm()
	if form.form_valid:
		if form.submit.data:
			option = form.create(poll_uid)
			option_history.OptionHistoryList.create(
				current_user.user.id, option.id, 'create'
			)
			return redirect(url_for('poll.get_option_catalog', poll_uid=poll_uid))
	return render_template(
		'option_form.html',
		form=form,
		action=blueprints.__('Create'),
		poll_uid=poll_uid
	)


@blueprint.route('/<poll_uid>/option/update/<uid>/', methods=('GET', 'POST'))
@permission_required
def update_option(poll_uid: str, uid: str):
	"""
	Return poll's option update page.
	"""
	form = option_form.OptionForm(uid)
	if form.form_valid:
		if form.submit.data:
			option = form.update(uid)
			option_history.OptionHistoryList.create(
				current_user.user.id, option.id, 'update'
			)
			return redirect(url_for('poll.get_option_catalog', poll_uid=poll_uid))
	return render_template(
		'option_form.html',
		form=form,
		action=blueprints.__('Update'),
		poll_uid=poll_uid
	)


@blueprint.route('/<poll_uid>/option/delete/<uid>/', methods=('GET',))
@permission_required
def delete_option(poll_uid: str, uid: str):
	"""
	Delete poll's option by uid and return redirect to option catalog.
	"""
	option = option_catalog.OptionList.delete(uid)
	option_history.OptionHistoryList.create(
		current_user.user.id, option.id, 'delete'
	)
	return redirect(url_for('poll.get_option_catalog', poll_uid=poll_uid))

source/blueprints/poll/templates/option_catalog.html
{%- extends "layout.html" -%}
{%- set hidden_content = True -%}
{%- set title = 'Poll Options' -%}
{%- block content -%}
	<div class="row row-cols-1 g-2 m-0">
		<div class="card shadow p-2 offset-1 col-10 offset-sm-2 col-sm-8 offset-md-3 col-md-6 offset-lg-4 col-lg-4">
			<div class="ui-background"></div>
			<div class="ui-foreground">
				<div class="row g-2">
					<div class="col-5 col-sm-5 col-md-4 col-lg-3">
						<div class="catalog-image">
							{%- if file -%}
								<img src="{{ url_for('root.download', uid=file.uid) }}"/>
							{%- endif -%}
						</div>
					</div>
					<div class="col-7 col-sm-7 col-md-8 col-lg-9">
						<div class="d-flex align-items-start flex-column h-100 w-100">
							<div class="d-flex justify-content-between align-items-center w-100">
								<h4 class="text-left">{{ poll.title }}</h4>
							</div>
							<div class="text-left">{{ poll.description }}</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="sortable" class="row row-cols-1 g-2 m-0">
		{%- if list|length -%}
			{%- for item, file in list -%}
				<div class="card shadow p-2 entity-uid" uid="{{ item.uid }}">
					<a href="{{ url_for('poll.update_option', poll_uid=poll.uid, uid=item.uid) }}" class="stretched-link"></a>
					<div class="ui-background"></div>
					<div class="ui-foreground">
						<div class="row g-2">
							<div class="col-12 col-sm-4 col-md-3 col-lg-2">
								<div class="catalog-image">
									{%- if file -%}
										<img src="{{ url_for('root.download', uid=file.uid) }}"/>
									{%- endif -%}
								</div>
							</div>
							<div class="col-12 col-sm-8 col-md-9 col-lg-10">
								<div class="d-flex align-items-start flex-column h-100 w-100">
									<div class="d-flex justify-content-between align-items-center w-100">
										<h4 class="text-left">{{ item.title }}</h4>
										<a class="nav-item pl-zero btn-in-stretched-link" href="#collapseDelete{{ item.uid }}" data-bs-toggle="collapse"><span class="nav-icon oi oi-x"></span><div class="d-none d-sm-inline">{{ __('Delete') }}</div></a>
									</div>
									<div class="collapse w-100 p-2 text-center collapse-message" id="collapseDelete{{ item.uid }}">
										<p class="mb-1"><small>{{ __('Do you really want to delete this option?') }}</small></p>
										<a class="btn btn-sm btn-outline-light btn-in-stretched-link" href="{{ url_for('poll.delete_option', poll_uid=poll.uid, uid=item.uid) }}">{{ '%s option' % __('Delete') }}</a>
										<a class="btn btn-sm btn-outline-light btn-in-stretched-link" href="#collapseDelete{{ item.uid }}" data-bs-toggle="collapse">{{ __('Cancel') }}</a>
									</div>
									<div class="text-left">{{ item.description }}</div>
									<div class="mt-auto d-flex justify-content-end text-muted align-items-center w-100">
										<small>
											{{ '%s: ' % __('Last modified') }}
											<div class="d-inline-block modified-timestamp">{{ '%s+0000' % item.modified_utc.isoformat(timespec='milliseconds') }}</div>
										</small>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			{%- endfor -%}
		{%- else -%}
			<div class="card shadow p-2">
				<div class="ui-background"></div>
				<div class="ui-foreground">
					<div class="text-center w-100">{{ __('No elements found') }}</div>
				</div>
			</div>
		{%- endif -%}
	</div>
	<div class="d-none">
		<form id="reordererForm" name="{{ reorderer.form_name }}" method="post" action="">
		 	{{ reorderer.csrf_token }}
			<input id="reordererFormData" name="{{ reorderer.data.label.text }}" type="text" value="{{ reorderer.data.data|default('', True) }}">
			<input id="reordererFormSubmitReal" name="{{ reorderer.submit.label.text }}" type="submit" value="{{ __('Submit') }}">
		</form>
	</div>
{%- endblock -%}
{%- set footer_collapse -%}
	<div id="collapseFilter" class="collapse ui-foreground">
		<form id="filterForm" name="{{ filter.form_name }}" method="post" action="">
		 	{{ filter.csrf_token }}
			<div class="row g-2 pt-2 pb-2">
				<div class="col-12 col-sm-12 col-md-5">
					<input autofocus name="{{ filter.title.label.text }}" class="form-control form-control-sm ui-input" type="text" placeholder="{{ __('Title') }}" aria-label="{{ __('Title') }}" value="{{ filter.title.data|default('', True) }}">
				</div>
				<div class="col-12 col-sm-8 col-md-5">
					<input name="{{ filter.description.label.text }}" class="form-control form-control-sm ui-input" type="text" placeholder="{{ __('Description') }}" aria-label="{{ __('Description') }}" value="{{ filter.description.data|default('', True) }}">
				</div>
				<div class="col-6 col-sm-2 col-md-1">
					<input default name="{{ filter.submit.label.text }}" class="w-100 btn btn-sm btn-outline-light" type="submit" value="{{ __('Apply') }}">
				</div>
				<div class="col-6 col-sm-2 col-md-1">
					<input name="{{ filter.reset.label.text }}" class="w-100 btn btn-sm btn-outline-light" type="submit" value="{{ __('Reset') }}">
				</div>
			</div>
		</form>
		<div class="collapse-separator"></div>
	</div>
{%- endset -%}
{%- set action_items -%}
	<a class="nav-item pl-zero" href="{{ url_for('poll.update', uid=poll.uid) }}"><span class="nav-icon oi oi-arrow-thick-left"></span><div class="d-none d-sm-inline">{{ __('Poll') }}</div></a>
	<div class="nav-separator"></div>
	<a class="nav-item pl-zero" href="#collapseFilter" data-bs-toggle="collapse"><span class="nav-icon oi oi-magnifying-glass"></span><div class="d-none d-sm-inline">{{ __('Filter') }}</div></a>
	<div class="nav-separator"></div>
	<a class="nav-item pl-zero" href="{{ url_for('poll.create_option', poll_uid=poll.uid) }}"><span class="nav-icon oi oi-plus"></span><div class="d-none d-sm-inline">{{ __('Create') }}</div></a>
	<label id="reordererFormSubmit" class="nav-item pl-zero" for="{{ reorderer.submit.label.text }}Real" onmouseover="" style="cursor: pointer;" tabindex=0><span class="nav-icon oi oi-loop-circular"></span><div class="d-none d-sm-inline">{{ __('Reorder') }}</div></label>
	<a class=" nav-item pl-zero" href="{{ url_for('poll.get_option_history', poll_uid=poll.uid) }}"><span class="nav-icon oi oi-script"></span><div class="d-none d-sm-inline">{{ __('Changes History') }}</div></a>
{%- endset -%}
{%- set additional_items -%}
	{%- if pagination.url_for_prev() -%}
		<a class="nav-item pl-zero" href="{{ pagination.url_for_prev() }}"><span class="nav-icon oi oi-chevron-left"></span><div class="d-none d-md-inline">{{ __('Previous') }}</div></a>
		<div class="nav-separator"></div>
	{%- endif -%}
	{%- if pagination.page_count > 1 -%}
		<div class="nav-item">
			{{ '%s: %d/%d' % (__('Page'), pagination.page_index, pagination.page_count) }}
			<div class="nav-separator"></div>
			<small class="d-none d-md-inline-block">{{ '%s: %d' % (__('Total elements'), pagination.entity_count) }}</small>
		</div>
	{%- elif pagination.entity_count > 0 -%}
		<div class="nav-item">{{ '%s: %d' % (__('Total elements'), pagination.entity_count) }}</div>
	{%- else -%}
		<div class="nav-item">{{ __('Empty list') }}</div>
	{%- endif -%}
	{%- if pagination.url_for_next() -%}
		<div class="nav-separator"></div>
		<a class="nav-item pr-zero" href="{{ pagination.url_for_next() }}"><div class="d-none d-md-inline">{{ __('Next') }}</div><span class="nav-icon oi oi-chevron-right"></span></a>
	{%- endif -%}
{%- endset -%}
{%- if not session.mobile -%}
	{%- block script -%}
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" integrity="sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA==" crossorigin="anonymous"></script>
		<script src="{{ url_for('static', filename='js/reordererForm.js') }}"></script>
	{%- endblock -%}
	{%- block body_script -%}
		<script type="text/javascript">
			$(function() {
				initSortable();
			});
		</script>
	{%- endblock -%}
{%- endif -%}

source/blueprints/poll/templates/poll_catalog.html
{%- extends "layout.html" -%}
{%- set hidden_content = True -%}
{%- set title = 'Polls' -%}
{%- block content -%}
	<div class="row row-cols-1 g-2 m-0">
		{%- if list|length -%}
			{%- for item, file in list -%}
				<div class="card shadow p-2 entity-uid" uid="{{ item.uid }}">
					<a href="{{ url_for('poll.update', uid=item.uid) }}" class="stretched-link"></a>
					<div class="ui-background"></div>
					<div class="ui-foreground">
						<div class="row g-2">
							<div class="col-12 col-sm-4 col-md-3 col-lg-2">
								<div class="catalog-image">
									{%- if file -%}
										<img src="{{ url_for('root.download', uid=file.uid) }}"/>
									{%- endif -%}
								</div>
							</div>
							<div class="col-12 col-sm-8 col-md-9 col-lg-10">
								<div class="d-flex align-items-start flex-column h-100 w-100">
									<div class="d-flex justify-content-between align-items-center w-100">
										<h4 class="text-left">{{ item.title }}</h4>
										<div>
											{%- if item.data_uid -%}
												<a class="nav-item pl-zero btn-in-stretched-link" href="{{ url_for('poll.stop', uid=item.uid) }}"><span class="nav-icon oi oi-media-pause"></span><div class="d-none d-sm-inline">{{ __('Stop') }}</div></a>
											{%- else -%}
												<a class="nav-item pl-zero btn-in-stretched-link" href="{{ url_for('poll.start', uid=item.uid) }}"><span class="nav-icon oi oi-media-play"></span><div class="d-none d-sm-inline">{{ __('Start') }}</div></a>
											{%- endif -%}
											<a class="nav-item pl-zero btn-in-stretched-link" href="#collapseDelete{{ item.uid }}" data-bs-toggle="collapse"><span class="nav-icon oi oi-x"></span><div class="d-none d-sm-inline">{{ __('Delete') }}</div></a>
										</div>
									</div>
									<div class="collapse w-100 p-2 text-center collapse-message" id="collapseDelete{{ item.uid }}">
										<p class="mb-1"><small>{{ __('Do you really want to delete this poll?') }}</small></p>
										<a class="btn btn-sm btn-outline-light btn-in-stretched-link" href="{{ url_for('poll.delete', uid=item.uid) }}">{{ '%s poll' % __('Delete') }}</a>
										<a class="btn btn-sm btn-outline-light btn-in-stretched-link" href="#collapseDelete{{ item.uid }}" data-bs-toggle="collapse">{{ __('Cancel') }}</a>
									</div>
									<div class="text-left">{{ item.description|default('', True) }}</div>
									<div class="collapse-separator mb-2"></div>
									{%- if item.vote_data and item.data_uid == None -%}
										{%- set results = __dict(item.vote_data)['results'] -%}
										<div class="row g-2 w-100">
											{%- for option in results -%}
												<div class="col-12 col-sm-6 col-md-4 col-lg-3">
													<div>{{ option['title'] }} - {{ option['percent'] }}% ({{ option['count'] }})</div>
												</div>
											{%- endfor -%}
										</div>
									{%- endif -%}
									<div class="mt-auto d-flex justify-content-end text-muted align-items-center w-100">
										<small>
											{{ '%s: ' % __('Last modified') }}
											<div class="d-inline-block modified-timestamp">{{ '%s+0000' % item.modified_utc.isoformat(timespec='milliseconds') }}</div>
										</small>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			{%- endfor -%}
		{%- else -%}
			<div class="card shadow p-2">
				<div class="ui-background"></div>
				<div class="ui-foreground">
					<div class="text-center w-100">{{ __('No elements found') }}</div>
				</div>
			</div>
		{%- endif -%}
	</div>
{%- endblock -%}
{%- set footer_collapse -%}
	<div id="collapseFilter" class="collapse ui-foreground">
		<form id="filterForm" name="{{ filter.form_name }}" method="post" action="">
		 	{{ filter.csrf_token }}
			<div class="row g-2 pt-2 pb-2">
				<div class="col-12 col-sm-12 col-md-5">
					<input autofocus name="{{ filter.title.label.text }}" class="form-control form-control-sm ui-input" type="text" placeholder="{{ __('Title') }}" aria-label="{{ __('Title') }}" value="{{ filter.title.data|default('', True) }}">
				</div>
				<div class="col-12 col-sm-8 col-md-5">
					<input name="{{ filter.description.label.text }}" class="form-control form-control-sm ui-input" type="text" placeholder="{{ __('Description') }}" aria-label="{{ __('Description') }}" value="{{ filter.description.data|default('', True) }}">
				</div>
				<div class="col-6 col-sm-2 col-md-1">
					<input default name="{{ filter.submit.label.text }}" class="w-100 btn btn-sm btn-outline-light" type="submit" value="{{ __('Apply') }}">
				</div>
				<div class="col-6 col-sm-2 col-md-1">
					<input name="{{ filter.reset.label.text }}" class="w-100 btn btn-sm btn-outline-light" type="submit" value="{{ __('Reset') }}">
				</div>
			</div>
		</form>
		<div class="collapse-separator"></div>
	</div>
{%- endset -%}
{%- set action_items -%}
	<a class="nav-item pl-zero" href="#collapseFilter" data-bs-toggle="collapse"><span class="nav-icon oi oi-magnifying-glass"></span><div class="d-none d-sm-inline">{{ __('Filter') }}</div></a>
	<div class="nav-separator"></div>
	<a class="nav-item pl-zero" href="{{ url_for('poll.create') }}"><span class="nav-icon oi oi-plus"></span><div class="d-none d-sm-inline">{{ __('Create') }}</div></a>
	<a class=" nav-item pl-zero" href="{{ url_for('poll.get_history') }}"><span class="nav-icon oi oi-script"></span><div class="d-none d-sm-inline">{{ __('Changes History') }}</div></a>
{%- endset -%}
{%- set additional_items -%}
	{%- if pagination.url_for_prev() -%}
		<a class="nav-item pl-zero" href="{{ pagination.url_for_prev() }}"><span class="nav-icon oi oi-chevron-left"></span><div class="d-none d-md-inline">{{ __('Previous') }}</div></a>
		<div class="nav-separator"></div>
	{%- endif -%}
	{%- if pagination.page_count > 1 -%}
		<div class="nav-item">
			{{ '%s: %d/%d' % (__('Page'), pagination.page_index, pagination.page_count) }}
			<div class="nav-separator"></div>
			<small class="d-none d-md-inline-block">{{ '%s: %d' % (__('Total elements'), pagination.entity_count) }}</small>
		</div>
	{%- elif pagination.entity_count > 0 -%}
		<div class="nav-item">{{ '%s: %d' % (__('Total elements'), pagination.entity_count) }}</div>
	{%- else -%}
		<div class="nav-item">{{ __('Empty list') }}</div>
	{%- endif -%}
	{%- if pagination.url_for_next() -%}
		<div class="nav-separator"></div>
		<a class="nav-item pr-zero" href="{{ pagination.url_for_next() }}"><div class="d-none d-md-inline">{{ __('Next') }}</div><span class="nav-icon oi oi-chevron-right"></span></a>
	{%- endif -%}
{%- endset -%}
{%- if not session.mobile -%}
	{%- block script -%}
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" integrity="sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA==" crossorigin="anonymous"></script>
		<script src="{{ url_for('static', filename='js/reordererForm.js') }}"></script>
	{%- endblock -%}
	{%- block body_script -%}
		<script type="text/javascript">
			$(function() {
				initSortable();
			});
		</script>
	{%- endblock -%}
{%- endif -%}